services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5173:5173"  # Vite開発サーバー用
    volumes:
      - .:/workspace:cached
      # 匿名ボリューム: 名前付きボリュームにすると、root権限で作成されてしまう
      - /workspace/node_modules
      # pnpmキャッシュを永続化
      - pnpm-store:/home/node/.local/share/pnpm/store
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
    command: ["pnpm", "dev"]

volumes:
  pnpm-store:
