CurrencySettings:
  type: object
  properties:
    base_currency:
      type: string
      description: 基準通貨
    auto_update:
      type: boolean
      description: 自動更新フラグ
    update_frequency:
      type: string
      description: 更新頻度
  required:
    - base_currency
    - auto_update
CurrencySettingsUpdateRequest:
  type: object
  properties:
    base_currency:
      type: string
      description: 基準通貨
    auto_update:
      type: boolean
      description: 自動更新フラグ
    update_frequency:
      type: string
      description: 更新頻度
  required:
    - base_currency
    - auto_update
PaymentMethod:
  type: object
  properties:
    id:
      type: string
      description: 支払い方法ID
    type:
      type: string
      description: 支払い方法タイプ
    card_brand:
      type: string
      description: カードブランド
    last_four_digits:
      type: string
      description: カード番号下4桁
    expiry_date:
      type: string
      description: 有効期限
    is_default:
      type: boolean
      description: デフォルトフラグ
  required:
    - id
    - type
    - is_default
PaymentMethodCreateRequest:
  type: object
  properties:
    card_number:
      type: string
      description: カード番号
    expiry_date:
      type: string
      description: 有効期限
    security_code:
      type: string
      description: セキュリティコード
    cardholder_name:
      type: string
      description: カード名義
  required:
    - card_number
    - expiry_date
    - security_code
    - cardholder_name
NotificationPreferences:
  type: object
  properties:
    channels:
      type: object
      properties:
        email:
          type: object
          properties:
            enabled:
              type: boolean
              description: 有効フラグ
            verified:
              type: boolean
              description: 検証済みフラグ
          required:
            - enabled
            - verified
        push:
          type: object
          properties:
            enabled:
              type: boolean
              description: 有効フラグ
            subscribed:
              type: boolean
              description: 購読済みフラグ
          required:
            - enabled
            - subscribed
      required:
        - email
        - push
    events:
      type: object
      properties:
        payment_due:
          type: object
          properties:
            enabled:
              type: boolean
              description: 有効フラグ
            reminder_days:
              type: array
              items:
                type: integer
              description: リマインダー日数
          required:
            - enabled
            - reminder_days
        trial_ending:
          type: object
          properties:
            enabled:
              type: boolean
              description: 有効フラグ
            reminder_days:
              type: array
              items:
                type: integer
              description: リマインダー日数
          required:
            - enabled
            - reminder_days
        payment_failed:
          type: object
          properties:
            enabled:
              type: boolean
              description: 有効フラグ
            retry_count:
              type: integer
              description: リトライ回数
          required:
            - enabled
            - retry_count
      required:
        - payment_due
        - trial_ending
        - payment_failed
  required:
    - channels
    - events
NotificationPreferencesUpdateRequest:
  type: object
  properties:
    channels:
      type: object
      properties:
        email:
          type: object
          properties:
            enabled:
              type: boolean
              description: 有効フラグ
        push:
          type: object
          properties:
            enabled:
              type: boolean
              description: 有効フラグ
    events:
      type: object
      properties:
        payment_due:
          type: object
          properties:
            enabled:
              type: boolean
              description: 有効フラグ
            reminder_days:
              type: array
              items:
                type: integer
              description: リマインダー日数
        trial_ending:
          type: object
          properties:
            enabled:
              type: boolean
              description: 有効フラグ
            reminder_days:
              type: array
              items:
                type: integer
              description: リマインダー日数
        payment_failed:
          type: object
          properties:
            enabled:
              type: boolean
              description: 有効フラグ
            retry_count:
              type: integer
              description: リトライ回数
